apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.user.svcName }}
  labels:
    {{- include "user.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30009
    targetPort: 8090
    protocol: TCP
  selector:
    {{- include "user.labels" . | nindent 4 }}
