apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.user.configMapName }}
data:
  E_COMM_DB_HOST: postgres-cont
  E_COMM_DB_PASS: password
  E_COMM_DB_USER: postgres
  E_COMM_DB_PORT: "5432"
  E_COMM_DB_NAME: postgres
  USER_SERVER_PORT: "8090"
  ORDER_SERVER_BASE_URL: http://order-svc:8091/
  USER_SERVER_EXISTS_URL: user/exists/