user:
  imageName: user-ms
  imageVer: latest
  svcName: user-svc
  configMapName: user-cm
  label:
    app: user-app

order:
  imageName: order-ms
  imageVer: latest
  svcName: order-svc
  configMapName: order-cm
  label:
    app: order-app

postgres:
  deployment:
    name: postgres-dep
  svcName: postgres-cont # DNS name
  port: 5432
  targetPort: 5432
  label:
    app: postgres-selector
  pv:
    name: postgres-pv
  pvc:
    name: postgres-pv-claim
    storage: 1Gi



# Default values for e-comm-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

ingress:
  enabled: true
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix
          backend:
          service:
            name: user-svc
            port:
              number: 8090
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
