apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-cm2
  labels:
    app: busybox-cm2
spec:
  selector:
    matchLabels:
      app: busybox-cm2
  template:
    metadata:
      labels:
        app: busybox-cm2
    spec:
      containers:
      - name: busybox
        image: busybox
        command: [ "/bin/sh","-c","mkdir /etc/velotio;" ]
        volumeMounts:
        - name: volume-configmap
          mountPath: "/etc/velotio"
          readOnly: true
      volumes:
      - name: volume-configmap
        configMap:
          name: cmvolume
